### ISSUE TITLE
missing Icons

### ISSUE THREAD

**Issue by bax-** [drewbkoch/Brackets-File-Icons#19]
Hi!

The following endings don't have an icon. They could use the regular ".txt" icon. Maybe add a wildcard property for all unknown file extensions?

.cfg
.mbm
.ckan
.cs
.skn
.csproj

files just named ".gitignore" don't have an icon as well.

Thank you!

**Comment by AdriVanHoudt** [comment]
Mine does ![](http://puu.sh/f60tJ/b6c142d77f.png)
Setting a default might not be a bad idea

**Comment by bax-** [comment]
you're right, mine works now too.
It might not? I wouldn't know why.

Oh and .dll also don't show any icon

**Comment by timbuktuuu** [comment]
But it's the wrong icon.. Its just showing the .txt icon on all .extensions

**Comment by AdriVanHoudt** [comment]
@bax- you can make a pr ;)
@timbuktuuu why is it wrong? If it are files like .gitignore anything can be in it.

**Comment by AdriVanHoudt** [comment]
hmm the examples work fine, looks like something goes wrong because brackets doesn't add an extension element with .gitignore files. Will look into it if I had the time.

**Comment by timbuktuuu** [comment]
Change it to something like file-icon:before could fix it but have to look at it later

**Comment by AdriVanHoudt** [comment]
It should default to the name of the file to match icon and then default to text icon

**Comment by AdriVanHoudt** [comment]
It is because how http://brackets.io/docs/current/modules/file/FileUtils.html#-getSmartFileExtension works. I'm working on a fix.

**Comment by AdriVanHoudt** [comment]
I added a PR https://github.com/drewbkoch/Brackets-File-Icons/pull/20

**Comment by bax-** [comment]
sounds great, thanks!
