### ISSUE TITLE
Icons padding need fix.

### ISSUE THREAD

**Issue by goliafrs** [drewbkoch/Brackets-File-Icons#31]
![image](https://cloud.githubusercontent.com/assets/6551082/20226516/75673068-a859-11e6-81c2-d9abe8630875.png)

Brackets version 1.8

**Comment by manuman94** [comment]
That's happening since the new Brackets Installation (1.8.0)

**Comment by gustavom** [comment]
Hello, I had this same problem. I do not know what your OS, but in windows, in the menu, click "help> show folder extension".

In the "user" folder, find the "Brackets Icons> styles" folder and add:

`.jstree-icon.file-icon{
    left: 18px !important;
}`

Here it worked, I opened a #33 pull request for this as well.

**Comment by gustavom** [comment]
Hello again.

Here's a much better solution:

`.jstree-icon.file-icon{
    position: relative;
    left: -5px !important;
}`

**Comment by venus-pixel** [comment]
Thanks @gustavom!!
this helped
